config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 root to: "pages#index"
 get '/about' => 'pages#about'
 resources :employees
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	validates :full_name, uniqueness: true
	validates :status, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def index
		@employees =Employee.all
	end
	def new
		@employee = Employee.new
	end 
	def create
		@employee = Employee.new(employee_params)
		if @employee.save
			redirect_to employees_path
		else
			@message = @employee.errors.messages
			render :new
		end
	end
	def edit
		@employee = Employee.find(params[:id])
	end

	def update
		@employee = Employee.find(params[:id])
		if @employee.update(employee_params)
			redirect_to employees_path
		else
			@message = @employee.errors.messages
			render :edit
		end
	end
	def destroy
		@employee = Employee.find(params[:id])
		@employee.destroy
		redirect_to employees_path
	end

	def show
		@employee = Employee.find(params[:id])
		@tax_witheld = 0
		@tax = 0
		@days = 314 - @employee.absences
		@salary = @employee.salary_per_day*@days
		@total_salary = @salary/12*@employee.number_of_months
		if @employee.number_of_months.to_i % 12 != 0
			if @employee.dependents == 0
				if @salary/12 <= 4167
					@tax_witheld = 0
				elsif @salary/12 < 5000
					@tax_witheld = (@salary/12-4167)*0.05
				elsif @salary/12 == 5000
					@tax_witheld = 41.67
				elsif @salary/12 <6667
					@tax_witheld = 41.67 + (@salary/12-5000)*0.1
				elsif @salary/12 == 6667
					@tax_witheld = 208.33
				elsif @salary/12 <10000
					@tax_witheld = 208.33+(@salary/12 - 6667)*0.15
				elsif @salary/12 == 10000
					@tax_witheld = 708.33
				elsif @salary/12 <15833
					@tax_witheld = 708.33+ (@salary/12 - 10000)*0.2
				elsif @salary/12 ==15833
					@tax_witheld = 1875
				elsif @salary/12 <25000
					@tax_witheld = 1875 + (@salary/12-15833)*0.25
				elsif @salary/12 == 25000
					@tax_witheld = 4166.67
				elsif @salary/12 <45833
					@tax_witheld = 4166.67 + (@salary/12-25000)*0.3
				elsif @salary/12 == 45833
					@tax_witheld = 10416.67
				else
					@tax_witheld = 10416.67 +(@salary/12-45833)*0.32
				end
			elsif @employee.dependents == 1
				if @salary/12 <= 6250
					@tax_witheld = 0
				elsif @salary/12 < 7083
					@tax_witheld = (@salary/12-6250)*0.05
				elsif @salary/12 == 7083
					@tax_witheld = 41.67
				elsif @salary/12 <8750
					@tax_witheld = 41.67 + (@salary/12-7083)*0.1
				elsif @salary/12 == 8750
					@tax_witheld = 208.33
				elsif @salary/12 <12083
					@tax_witheld = 208.33+(@salary/12 - 8750)*0.15
				elsif @salary/12 == 12083
					@tax_witheld = 708.33
				elsif @salary/12 <17917
					@tax_witheld = 708.33+ (@salary/12 - 12083)*0.2
				elsif @salary/12 ==17197
					@tax_witheld = 1875
				elsif @salary/12 <27083
					@tax_witheld = 1875 + (@salary/12-17917)*0.25
				elsif @salary/12 == 27083
					@tax_witheld = 4166.67
				elsif @salary/12 <47197
					@tax_witheld = 4166.67 + (@salary/12-27083)*0.3
				elsif @salary/12 == 47917
					@tax_witheld = 10416.67
				else
					@tax_witheld = 10416.67 +(@salary/12-47917)*0.32
				end
			elsif @employee.dependents ==2 
				if @salary/12 <= 8333
					@tax_witheld = 0
				elsif @salary/12 < 9167
					@tax_witheld = (@salary/12-8333)*0.05
				elsif @salary/12 == 9167
					@tax_witheld = 41.67
				elsif @salary/12 <10833
					@tax_witheld = 41.67 + (@salary/12-9167)*0.1
				elsif @salary/12 == 10833
					@tax_witheld = 208.33
				elsif @salary/12 <14167
					@tax_witheld = 208.33+(@salary/12 - 10833)*0.15
				elsif @salary/12 == 14167
					@tax_witheld = 708.33
				elsif @salary/12 <20000
					@tax_witheld = 708.33+ (@salary/12 - 14167)*0.2
				elsif @salary/12 ==20000
					@tax_witheld = 1875
				elsif @salary/12 <29167
					@tax_witheld = 1875 + (@salary/12-20000)*0.25
				elsif @salary/12 == 29167
					@tax_witheld = 4166.67
				elsif @salary/12 <50000
					@tax_witheld = 4166.67 + (@salary/12-29167)*0.3
				elsif @salary/12 == 50000
					@tax_witheld = 10416.67
				else
					@tax_witheld = 10416.67 +(@salary/12-50000)*0.32
				end
			elsif @employee.dependents ==3 
				if @salary/12 <= 10417
					@tax_witheld = 0
				elsif @salary/12 < 11250
					@tax_witheld = (@salary/12-10417)*0.05
				elsif @salary/12 == 11250
					@tax_witheld = 41.67
				elsif @salary/12 <12917
					@tax_witheld = 41.67 + (@salary/12-11250)*0.1
				elsif @salary/12 == 12917
					@tax_witheld = 208.33
				elsif @salary/12 <16250
					@tax_witheld = 208.33+(@salary/12 - 12917)*0.15
				elsif @salary/12 == 16250
					@tax_witheld = 708.33
				elsif @salary/12 <22083
					@tax_witheld = 708.33+ (@salary/12 - 16250)*0.2
				elsif @salary/12 ==22083
					@tax_witheld = 1875
				elsif @salary/12 <31250
					@tax_witheld = 1875 + (@salary/12-22083)*0.25
				elsif @salary/12 == 31250
					@tax_witheld = 4166.67
				elsif @salary/12 <52083
					@tax_witheld = 4166.67 + (@salary/12-31250)*0.3
				elsif @salary/12 == 52083
					@tax_witheld = 10416.67
				else
					@tax_witheld = 10416.67 +(@salary/12-52083)*0.32
				end
			else
				if @salary/12 <= 12500
					@tax_witheld = 0
				elsif @salary/12 < 13333
					@tax_witheld = (@salary/12-12500)*0.05
				elsif @salary/12 == 13333
					@tax_witheld = 41.67
				elsif @salary/12 <15000
					@tax_witheld = 41.67 + (@salary/12-13333)*0.1
				elsif @salary/12 == 15000
					@tax_witheld = 208.33
				elsif @salary/12 <18333
					@tax_witheld = 208.33+(@salary/12 - 15000)*0.15
				elsif @salary/12 == 18333
					@tax_witheld = 708.33
				elsif @salary/12 <24167
					@tax_witheld = 708.33+ (@salary/12 - 18333)*0.2
				elsif @salary/12 ==24167
					@tax_witheld = 1875
				elsif @salary/12 <33333
					@tax_witheld = 1875 + (@salary/12-24167)*0.25
				elsif @salary/12 == 33333
					@tax_witheld = 4166.67
				elsif @salary/12 <54167
					@tax_witheld = 4166.67 + (@salary/12-33333)*0.3
				elsif @salary/12 == 54167
					@tax_witheld = 10416.67
				else
					@tax_witheld = 10416.67 +(@salary/12-54167)*0.32
				end
			end
			if @employee.number_of_months >= 12
				if @salary <= 10000
			@tax = @salary*0.05
		elsif @salary>10000 && @salary<=30000
			@tax = (500+0.10*(@salary-10000))
		elsif @salary>30000 && @salary<=70000
			@tax = (2500 + 0.15*(@salary-30000))
		elsif @salary>70000 && @salary<=140000
			@tax = (8500 +0.20*(@salary-70000))
		elsif @salary>140000 && @salary<=250000
			@tax = (22500 + 0.25*(@salary-140000))
		elsif @salary>250000 && @salary <=500000
			@tax = (50000 + 0.3*(@salary-250000))
		else
			@tax = (125000 + 0.32*(@salary-500000))
		end
	end
		else
		if @salary <= 10000
			@tax = @salary*0.05
		elsif @salary>10000 && @salary<=30000
			@tax = (500+0.10*(@salary-10000))
		elsif @salary>30000 && @salary<=70000
			@tax = (2500 + 0.15*(@salary-30000))
		elsif @salary>70000 && @salary<=140000
			@tax = (8500 +0.20*(@salary-70000))
		elsif @salary>140000 && @salary<=250000
			@tax = (22500 + 0.25*(@salary-140000))
		elsif @salary>250000 && @salary <=500000
			@tax = (50000 + 0.3*(@salary-250000))
		else
			@tax = (125000 + 0.32*(@salary-500000))
		end
	end
	if @employee.number_of_months >= 12 
	if @tax*(@employee.number_of_months/12).to_i < @tax_witheld*@employee.number_of_months.to_i && @tax !=0
		@net_salary = @total_salary + (@tax_witheld*@employee.number_of_months - @tax)
	elsif @tax*(@employee.number_of_months/12).to_i == 0
		@net_salary = @total_salary - @taxwitheld*@employee.number_of_months
	else
		@net_salary = @total_salary - (@tax*(@employee.number_of_months/12).to_i - @tax_witheld*@employee.number_of_months)
	end
else
	@net_salary = @total_salary - @tax_witheld
end

		render :show 
		
	end
def employee_params
		params.require(:employee).permit!
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@latest_employees = Employee.last(5)
	end
	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employees/_employee.html.erb
<hr>
<h4><%= employee.full_name %></h4>
<div>
<b>Salary Per Day:</b> <%= employee.salary_per_day %>
</div>
<hr>

app/views/employees/_form.html.erb
<%= simple_form_for @employee do |f| %>
	<%= f.input :full_name, required: true %>
	<%= f.input :age, as: :integer, required: true  %>
	<%= f.input :dependents, as: :integer, required: true %>
	<%= f.input :salary_per_day, as: :float, required: true %>
	<%= f.input :number_of_months, as: :integer, required: true %>
	<%= f.input :absences, as: :integer, required: true %>
	Status <br>
	<%= f.select :status, ['Single', 'Married'], :prompt => 'Select One', required: true %>
	<br>
	<%= f.submit "Save" %>
<% end %>

app/views/employees/compute.html.erb
<h1>Total Salary<h1>
<hr>
<h1><%= @employee.full_name %></h1>
<hr>
<h2><%= @salary %>

app/views/employees/edit.html.erb
<br><br><h1>Edit Employee</h1>
<hr>
<%= render partial: "employees/form", locals: { employee: @employee } %>

app/views/employees/form.html.erb
<%= simple_form_for @employee do |f| %>
	<%= f.input :full_name, required: true %>
	<%= f.input :age, as: :integer, required: true  %>
	<%= f.input :dependents, as: :integer, required: true %>
	<%= f.input :salary_per_day, as: :float, required: true %>
	<%= f.input :month, as: :integer, required: true %>
	<%= f.input :absences, as: :integer, required: true %>
	<%= f.input :status, as: :string, required: true %>
	<hr>
	<%= f.submit "Save" %>
<% end %>

app/views/employees/index.html.erb
<br><br><h1>Employees</h1>
<hr>
<%= link_to "New Employee", new_employee_path %>
<hr>

<table class="table table-striped">
	<thead>
		<tr><b>
			<td><b>Full Name</b></td>
			<td><b>Show</b></td>
			<td><b>Edit</b></td>
			<td><b>Fire</b></td>
		</tr></b>
	</thead>
	<tbody>
		<% @employees.each do |employee| %>
		<tr>
			<td><%= employee.full_name %></td>
			<td><%= link_to "Show", employee_path(employee.id) %></td>
			<td><%= link_to "Edit", edit_employee_path(employee.id) %></td>
			<td><%= link_to "Fire", employee_path(employee.id), method: :delete, data: { confirm: "Are you sure you want to fire this employee?" } %><br></td>
		</tr>
	</tbody>
	<% end %>
</table>

app/views/employees/new.html.erb
<br><br><h1>New Employee</h1>
<hr>
<% if !@message.nil? %>
	<%= @message %>
<% end %>
<%= render partial: "employees/form", locals: { employee: @employee} %>

app/views/employees/show.html.erb
<h1><%= @employee.full_name %></h1><hr><br>
<h4>Salary Per Day:</h4> <h5>P<%= @employee.salary_per_day %></h5><br>
<h4>Number of Months:</h4> <h5><%= @employee.number_of_months %><h5>
<hr>
<h2> Summary: </h2>	
<table class="table table-striped">
	<thead>
		<tr>
			<td><b>Total Salary</b></td>
			<td><b>Tax Withheld<b></td>
			<td><b>Tax for the Year<b></td>
			<td><b>Net Salary<b></td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>P<%= @total_salary %></td>
			<% if @employee.number_of_months <12 %>
				<td>P<%= @tax_witheld*@employee.number_of_months.to_i %></td>
			<% else %>
				<td>P<%= @tax_witheld*((@employee.number_of_months.to_i)%12) %> </td>
			<% end %>
			
			<td>P<%= @tax*(@employee.number_of_months/12).to_i %></td>
			<td>P<%= @net_salary %></td>
		</tr>
	</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Payroll" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <p class="navbar-text pull-right">
    <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Payroll</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "List of Employees", employees_path  %></li>
              <li><%= link_to "Hire New Employees", new_employee_path  %></li>
              <li><a href="/about">About Us</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<br><br><br>
    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                
                <li><%= link_to "List of Employees", employees_path  %></li>
              <li><%= link_to "Hire New Employees", new_employee_path  %></li>
              <li><a href="/about">About Us</a></li>
              </ul>
            </div><!--/.well -->
            <br><br> <img src ="/images/money.jpg" align= "right"/>
          </div><!--/span-->
        </div><!--/row-->
      <footer>
        <p>&copy; LaoLim 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/about.html.erb
<h1>About the Developer</h1>
<hr>
<center><img src ="/images/earvin.jpg" alt="earvin feed" width=35% height=35% /> <img src ="/images/guerric.jpg" alt="guerric feed" width=35% height=35% /></center>
<center><h1>Earvin lao & Guerric Lim</h1></center> 
<p>Earvin Lao was just a young boy when he decided to take computer programming as his course in college. Because of his innate desire to create programs and also websites, he studied very hard. Now that he had graduated top 5 in his batch, he can already fulfill his dream of being a professional. </p>
<p>5 years after, he now has a family with two children. His wife is named Ellyse Marie Ibay. <center><img src ="/images/lace.jpg" alt="lace feed" width=35% height=35% /></p></center>
<p>Because of his excellent career, his family never worried about financial matters. In his journey through life, he met another successful person, namely, Guerric Lim.</p>
<p> Another 5 years later, Earvin and Guerric became close friends to the point where they decided to put up their own firm that creates well-functioning programs for the public to use. One of their projects is this website called the "Payroll". They decided to create this website because they wanted to make the employers' lives much much easier. Having this website, they can easiy calculate the income of their employees and also the taxes invloved. This website turned into a great success which created profit for their joint business. </p>

app/views/pages/index.html.erb
<h1>Employees</h1>
<hr>

<h2>Latest Employees</h2>

<% @latest_employees.each do |r| %>
	<%= render partial: "employees/employee", locals: { employee: r } %>
<% end %>